Introduce apprentice limit to disable lessons
davidsansome/tsurukame pull request #441
Opened 2021-03-14 21:54 UTC by ShaneCoufreur

2021-03-15 01:20 UTC, UInt2048 commented
@ShaneCoufreur Haven't had time to review this, but if you remove the word "for" it will auto-close the issue if merged

2021-03-19 08:58 UTC, davidsansome requested changes

2021-03-19 08:58 UTC, davidsansome commented on ios/SettingsViewController.swift
> +      : "Disabled"
I wonder if "Disabled" sounds a bit technical. Maybe just "-" or "None" would work better?

2021-03-19 08:58 UTC, davidsansome commented on ios/TKMLessonApprenticeLimitViewController.m
> +// Copyright 2020 David Sansome
Would you be able to rewrite this in Swift instead? I'm trying not to introduce any new Objective-C

2021-03-23 09:26 UTC, ShaneCoufreur commented on ios/TKMLessonApprenticeLimitViewController.m
> +// Copyright 2020 David Sansome
I'll see if I can brush up on some Swift soon. Don't have a whole lot of experience with it, but will see what I can do.

2021-04-06 16:45 UTC, UInt2048 commented
I rewrote the Objective-C in Swift - see #450

2021-04-07 01:08 UTC, closed without merging