Sequential audio playback
davidsansome/tsurukame pull request #465
Opened 2021-05-25 21:41 UTC by realericmc

added playing audio readings sequentially, and a setting to pick if they should be random

2021-05-26 14:55 UTC, realericmc commented
not sure about this bundle test failure.  I didn't think I included anything that would affect this.  That said, it has been a while since I messed with GitHub so any comments on this would be appreciated.

2021-05-26 15:36 UTC, UInt2048 commented
@realericmc I got tests working with a one-line commit: 368c7b766848d26158a242ea278785475b519d53

Please accept realericmc/tsurukame#1

2021-05-26 16:16 UTC, UInt2048 commented
@realericmc You just got unlucky, this test failure would have occurred to whoever submitted the next PR/commit.

I didn't test anything else in your PR though, apart from the one-line CI fix.

2021-05-26 16:18 UTC, realericmc commented
good to know I wasn't going crazy at least.  thanks for running that down!

2021-06-14 00:44 UTC, davidsansome requested changes

2021-06-14 00:44 UTC, davidsansome commented on ios/SettingsViewController.swift
> +    model.add(TKMSwitchModelItem(style: .subtitle,
I don't think it makes sense to expose this as a setting. The "order" of the audio IDs in the proto is arbitrary so I don't think it's something that users should have to decide about. I suspect this PR is more about avoiding having the same speaker play twice in a row?

How about removing the random option entirely, and making sequential playback the default?

2021-06-14 00:44 UTC, davidsansome commented on ios/WaniKaniAPI/Sources/WaniKaniAPI/ProtobufExtensions.swift
> +      static var idx: Int = 0
I don't really like the static variable here. I would remove this function (as well as `randomAudioID`) entirely, and then add a `private var lastPlayedAudioIndex` to the `Audio` class, and do this logic in `Audio`'s `play` method.

2021-06-14 15:58 UTC, UInt2048 commented
I think I implemented the requested changes. I have a direct PR to this repo in #466, as well as a PR to this PR in realericmc#2

2021-06-15 18:45 UTC, realericmc commented on ios/WaniKaniAPI/Sources/WaniKaniAPI/ProtobufExtensions.swift
> +      static var idx: Int = 0
agree, I like your way better also

2021-06-16 01:27 UTC, UInt2048 commented
@davidsansome The requested changes have been implemented.

2021-06-16 04:10 UTC, merged