Add option for viewing current level graph before finishing vocab
davidsansome/tsurukame pull request #606
Opened 2023-01-02 17:11 UTC by Deadpikle

One downside to passing kanji is that you level up before you finish vocabulary. For those of us who are ordering things such that we finish vocab before we start the next level's radicals/kanji, it would be useful to see a graph of our current progress.

This PR adds a setting to enable that. If active, it will check to see if the user's previous level (the one where they have vocabulary) is done or not. If it is not done, a second graph is shown on the home screen with the title `Current Level (#)`, and then the user's _actual_ current level graph is titled with `Next Level`. If the setting is on and the user has finished the prior level, it will only show the current level's graph.

I also renamed `This Level` to `Current Level` if the setting is off (or does not apply); that is more of a subjective change that doesn't necessarily need to come in. I just thought it would make sense if we always have "current level" and "next level", as if the user is done with the prior level, the section title would change from "Next Level" to "This Level", which might end up being confusing.

![Simulator Screen Shot - iPhone SE (2nd generation) - 2023-01-02 at 12 00 12](https://user-images.githubusercontent.com/5092399/210261074-e4d5b45e-00b9-494a-a83b-3d0d6417206e.png)

![Simulator Screen Shot - iPhone SE (2nd generation) - 2023-01-02 at 12 00 19](https://user-images.githubusercontent.com/5092399/210261130-ad6ae93e-db6e-47d9-b920-7f415014ff2c.png)

2023-01-03 08:38 UTC, davidsansome requested changes

2023-01-03 08:38 UTC, davidsansome commented on ios/LocalCachingClient.swift
> +        isDoneWithPreviousLevel = false
You can exit early here, just `return false` and ditch the `isDoneWithPreviousLevel` variable.

Alternatively, if you think it's more readable, you could try something like:

```
return !assignments.contains { !$0.hasPassedAt }
```

2023-01-03 08:38 UTC, davidsansome commented on ios/LocalCachingClient.swift
> +      if assignment.srsStageNumber == level, !assignment.hasPassedAt {
The `srsStageNumber` is the Apprentice, Guru... stage number, **not** the user's level. You can't compare the two like this.

If you're trying to check whether the assignment is past Guru, you can do `if assignment.srsStage >= .guru1`.

But, is that even necessary since we're checking `hasPassedAt` anyway?

2023-01-03 08:38 UTC, davidsansome commented on ios/LocalCachingClient.swift
> +  func getAssignmentsAtUsersCurrentGraphLevel() -> [TKMAssignment] {
I'm not sure this function is necessary. MainViewController is doing all these checks anyway, so let's just delete this function and make it do `services.localCachingClient.getAssignments(level: user.currentLevel - 1)`

2023-01-03 08:38 UTC, davidsansome commented on ios/MainViewController.swift
> +      model.add(section: "Next level")
It might be nice to put the next level number in parentheses here too.

2023-01-03 08:38 UTC, davidsansome commented on ios/MainViewController.swift
> +
Can we have "Show remaining" and "Show all" buttons for the current level? It might need a bit of refactoring.

2023-01-03 08:38 UTC, davidsansome commented on ios/Settings.swift
> +  @Setting(false, #keyPath(showPreviousLevelGraph)) static var showPreviousLevelGraph: Bool
I'd probably have this default to true tbh - it seems really useful, and people are unlikely to discover it otherwise.

2023-01-07 23:58 UTC, Deadpikle commented on ios/MainViewController.swift
> +
`SubjectCatalogueViewController` already took a level as a param so this didn't take much work.

`SubjectsRemainingViewController` was refactored to take the user's level and then pulling in vocabulary into the list if the setting for this PR (`showPreviousLevelGraph`) is `true`.

I thought about using some new segues in the storyboard to help know which level a user was tapping on, but decided that two new `var` in the `MainViewController` was much simpler and less confusing.

2023-01-07 23:59 UTC, Deadpikle commented on ios/LocalCachingClient.swift
> +        isDoneWithPreviousLevel = false
I went with the latter syntax you recommended. I'm (historically) an Objective-C user, and haven't used Swift really much at all, so I'll lean on your experience for the syntax there being widely used. (The `$0` syntax was understood after a quick google search, so shouldn't be a big deal.)

2023-01-08 00:02 UTC, Deadpikle commented
Thanks for the very quick review! (I'm usually fairly busy, so sometimes these things take me some time. If you want to handle anything in this or the other PR without waiting for me, please do! Otherwise, will try to be relatively quick.)

Here's a GIF of this working:

![two-levels-at-once](https://user-images.githubusercontent.com/5092399/211174675-083a8370-be70-457c-ab4b-1bc3bd262860.gif)

2023-01-09 09:28 UTC, davidsansome commented
> Thanks for the very quick review! (I'm usually fairly busy, so sometimes these things take me some time. If you want to handle anything in this or the other PR without waiting for me, please do! Otherwise, will try to be relatively quick.)

No worries, thanks for addressing the comments!

> Here's a GIF of this working:

Looks great :)

> I'm not sure why the "Next level-up review" is set to "Now". Is that expected behavior? Doesn't seem to be affected by anything in this PR, though, so I'll write that off for the moment.

Hmm I'm not sure, is it because you still have 1 kanji left in level 3, and it's ready for review now? I would've thought it should be looking at the level 4 list though.

2023-01-09 09:29 UTC, davidsansome commented on ios/SubjectsRemainingViewController.swift
> +    navigationItem.title = "Remaining in Level \(level!)"
You probably don't need the `!` here, since the variable is defined as an `Int!` already.

2023-01-09 09:29 UTC, davidsansome commented on ios/MainViewController.swift
> +  var isShowingPriorUserLevel = false
These two variables feel a bit icky to me. What about having a single `selectedSubjectCatalogLevel`, and setting it in the tap handler.

`addShowRemainingAllItems` would need to take a `level` parameter, and it can use the new syntax for `BasicModelItem` tap handlers, like this:

```
    model.add(BasicModelItem(style: .default,
                             title: "Show remaining",
                             subtitle: nil,
                             accessoryType: .disclosureIndicator) {
      this.selectedSubjectCatalogLevel = level
      performSegue(withIdentifier: "showRemaining", sender: self)
    })
```

Then you can delete the `showRemaining` and `showAll` functions as well.

2023-01-22 16:19 UTC, Deadpikle commented on ios/SubjectsRemainingViewController.swift
> +    navigationItem.title = "Remaining in Level \(level!)"
I see exactly what you mean here, and I would imagine you'd be correct, but removing the `!` results in [this warning](https://stackoverflow.com/questions/42543007/how-to-solve-string-interpolation-produces-a-debug-description-for-an-optional). So, I opted for removing the `!` and just doing `private var level: Int = 0`. ....not sure if that is any better. I'll leave that one for your judgment call.

I'm on Xcode 12.2 with no real option to update right now, which is unfortunate, as that may be causing the problem (grumble grumble, why are Xcode updates so terribly large). Sorry about that.

2023-01-22 16:39 UTC, Deadpikle commented
Again, apologies for the slow here. Life and other priorities. Let me know if this or the other PR need changes or if they're good to go now. :)

2023-02-12 04:22 UTC, merged