Add ArtWork by @AmandaBear to Subject
davidsansome/tsurukame pull request #653
Opened 2023-07-23 04:10 UTC by tallerasaf

Add helpful artwork for a subject.

WK Mnemonic “Art” for Kanji Levels 1-7 (Radical Levels 1-10)

Based on this userscript, by @Sinyaven:
https://greasyfork.org/en/scripts/418774-wanikani-mnemonic-artwork 

@AmandaBear consent:
Feel free to do whatever you want with my images. I only made them for fun and to help others learn the mnemonics.
Go right ahead. I give my full permission to use my images. 
I waive all rights to all my WaniKani radical and kanji drawings, including all those posted and linked at WK Mnemonic "Art" for Kanji Levels 1-7 (Radical Levels 1-10) , under the CC0 public domain dedication (Creative Commons — CC0 1.0 Universal).

![Example ScreenShot](https://github.com/davidsansome/tsurukame/assets/14837253/2993064a-f977-49cc-8e2e-83e859c2204e)

2023-07-23 04:11 UTC, tallerasaf commented
@indirect @UInt2048 @davidsansome Can you take a look?
Thanks!

2023-07-23 09:30 UTC, UInt2048 commented on ios/SubjectDetailsView.swift
> +    if #available(iOS 15.0, *), ArtworkManager.contains(subjectID: subject.id) {
Looks like you have a failing test here.

Also, maybe we should have a setting for whether to add the artwork model item?

2023-07-23 17:36 UTC, tallerasaf commented on ios/SubjectDetailsView.swift
> +    if #available(iOS 15.0, *), ArtworkManager.contains(subjectID: subject.id) {
@UInt2048 Do you know why I have this issue?
In my XCode on my Machine "Profuct -> Run" and "Product -> Test" Works.

[04:16:26]: ▸ ❌  /Users/distiller/project/ios/SubjectDetailsView.swift:493:33: cannot find 'ArtworkManager' in scope
[04:16:26]: ▸     if #available(iOS 15.0, *), ArtworkManager.contains(subjectID: subject.id) {
[04:16:26]: ▸                            ^~~~
[04:16:26]: ▸ ❌  /Users/distiller/project/ios/SubjectDetailsView.swift:495:17: cannot find 'ArtworkModelItem' in scope
[04:16:26]: ▸       model.add(ArtworkModelItem(subjectID: subject.id))

Testing failed:
	Cannot find 'ArtworkManager' in scope
	Cannot find 'ArtworkModelItem' in scope

2023-07-23 23:38 UTC, tallerasaf commented on ios/SubjectDetailsView.swift
> +    if #available(iOS 15.0, *), ArtworkManager.contains(subjectID: subject.id) {
> Also, maybe we should have a setting for whether to add the artwork model item?

Done:
![[Toggle option in Settings for the ArtWork Section](https://github.com/davidsansome/tsurukame/pull/653/commits/721ac02b54595a7311aa2707fe164c10ef449444)](https://github.com/davidsansome/tsurukame/assets/14837253/c3dfc664-9446-49b1-b833-8f0a7a7ee139)

2023-07-23 23:40 UTC, tallerasaf commented on ios/SubjectDetailsView.swift
> +    if #available(iOS 15.0, *), ArtworkManager.contains(subjectID: subject.id) {
> Also, maybe we should have a setting for whether to add the artwork model item?

@UInt2048 Do you know why I have this issue?  In my XCode on my Machine "Profuct -> Run" and "Product -> Test" everything is working.

[04:16:26]: ▸ ❌ /Users/distiller/project/ios/SubjectDetailsView.swift:493:33: 
cannot find 'ArtworkManager' in scope [04:16:26]: ▸ if #available(iOS 15.0, *), ArtworkManager.contains(subjectID: subject.id) { [04:16:26]: ▸ ^~~~ [04:16:26]: ▸ ❌ /Users/distiller/project/ios/SubjectDetailsView.swift:495:17: 
cannot find 'ArtworkModelItem' in scope [04:16:26]: ▸ model.add(ArtworkModelItem(subjectID: subject.id))
Testing failed: Cannot find 'ArtworkManager' in scope 
Cannot find 'ArtworkModelItem' in scope

2023-07-25 13:25 UTC, UInt2048 commented on ios/SubjectDetailsView.swift
> +    if #available(iOS 15.0, *), ArtworkManager.contains(subjectID: subject.id) {
@tallerasaf I don't see a change to project.pbxproj even though you created new files, so Xcode is unaware of their existence.

2023-07-25 13:40 UTC, UInt2048 requested changes

2023-07-25 13:40 UTC, UInt2048 commented on ios/Settings.swift
> +  @Setting(true, #keyPath(showArtWork)) static var showArtWork: Bool
Tsurukame precedent is to have new settings have the same value as the equivalent behavior in previous releases, so the default should be false here.

Also, it appears you're introducing a new feature that only works online for a small minority of items unlike every other feature in the app that works offline for all items (and only on iOS 15+ for what it's worth).

I'm not David Sansome and don't have any say over merging, but are you sure this is something that needs to be added?

2023-07-26 00:06 UTC, tallerasaf commented on ios/SubjectDetailsView.swift
> +    if #available(iOS 15.0, *), ArtworkManager.contains(subjectID: subject.id) {
@UInt2048 I added project.pbxproj file, thanks!

2023-07-26 00:07 UTC, tallerasaf commented on ios/Settings.swift
> +  @Setting(true, #keyPath(showArtWork)) static var showArtWork: Bool
> Tsurukame precedent is to have new settings have the same value as the equivalent behavior in previous releases, so the default should be false here.

@UInt2048 I changed the default setting to false now.

2023-07-26 00:20 UTC, tallerasaf commented on ios/Settings.swift
> +  @Setting(true, #keyPath(showArtWork)) static var showArtWork: Bool
> Also, it appears you're introducing a new feature that only works online for a small minority of items unlike every other feature in the app that works offline for all items (and only on iOS 15+ for what it's worth).
It works only online but the WaniKaniApi works only online too.
It is not a small minority of items for beginners, it has all the radicals and kanji until level 7 so it's very useful and especially for people who are just starting because WaniKani is entirely textual, for many people visuals can help a lot to remember.
The ArtWork by @AmandaBear really helps to remember the mnemonics visually.

> I'm not David Sansome and don't have any say over merging, but are you sure this is something that needs to be added?
I think it's a nice feature because tsurukame is entirely textual so it makes the App more fun with the added visual ArtWorks and it is disabled by default so only people who want this will have it.

2023-07-26 21:01 UTC, UInt2048 commented on ios/Settings.swift
> +  @Setting(true, #keyPath(showArtWork)) static var showArtWork: Bool
@tallerasaf People can do lessons offline and might be confused why your feature isn't working. I don't think Mr. Sansome wants that maintenance burden (cf. #524).

2023-07-26 21:03 UTC, UInt2048 reviewed
Those changes look better — tests are passing now.

2023-12-30 22:51 UTC, davidsansome requested changes
Sorry for not looking at this PR sooner!

It looks good - just a couple of minor comments!

2023-12-30 22:51 UTC, davidsansome commented on ios/Tables/ArtworkModelItem.swift
> +  private func setupUI() {
Can you delete this method if it's empty?

2023-12-30 22:51 UTC, davidsansome commented on ios/SubjectDetailsSettingsViewController.swift
> +                                title: "Show ArtWork by @AmandaBear",
Tiny inconsequential nit: "Artwork" is one word so the "W" shouldn't be captialised. Can you make sure it's "Artwork" everywhere in this PR? I think it's just this file, Settings.swift, and the section header SubjectDetailsView.swift that need changing!

2023-12-30 22:51 UTC, davidsansome commented on ios/Tables/ArtworkManager.swift
> +    let monitor = NWPathMonitor()
I was going to suggest using `services.reachability.isReachable()` but it looks like `NWPathMonitor` is better so we should probably actually be using it everywhere instead!

2023-12-30 22:51 UTC, davidsansome commented on ios/Tables/ArtworkManager.swift
> +  static let artworkURLs: [Int64: String] = [
Did you have a script that generated this mapping? It might be useful to link it here (or include it in this PR) so it can be regenerated if the URLs change or if new subjects are added.

2023-12-31 05:05 UTC, tallerasaf commented on ios/Tables/ArtworkManager.swift
> +  static let artworkURLs: [Int64: String] = [
I added to this file.

2023-12-31 05:08 UTC, tallerasaf commented on ios/Tables/ArtworkManager.swift
> +    let monitor = NWPathMonitor()
Add to Audio.swift too

2023-12-31 05:14 UTC, tallerasaf commented on ios/SubjectDetailsSettingsViewController.swift
> +                                title: "Show ArtWork by @AmandaBear",
Done

2023-12-31 05:15 UTC, tallerasaf commented on ios/Tables/ArtworkModelItem.swift
> +  private func setupUI() {
Done

2023-12-31 05:19 UTC, tallerasaf reviewed
Fix davidsansome comments.

2024-01-01 02:17 UTC, merged

2024-01-01 23:27 UTC, aaron-meyers commented
@tallerasaf @davidsansome @UInt2048 I just saw this in the TestFlight build and turned it on but couldn't get it to work on my iPhone. Running latest iOS, iPhone 12 mini. Not sure what's going on.

That said, I'd like to propose that Tsurukame adopt the much broader AI mnemonic images project that has been ongoing for the last 1+ year. This project has already produced hundreds of images and has had a lot of renewed interest with the release of the highly capable DALL-E 3 image generation model. The community post about the project is here (with link to the Discord server for submitting and voting on images): https://community.wanikani.com/t/new-volunteer-project-were-using-ai-to-create-mnemonic-images-for-every-radical-kanji-vocabulary-come-join-us/58234

And the userscript that implements it is here (also in the community post of course): https://greasyfork.org/en/scripts/448713-wanikani-ai-mnemonic-images

It should be a fairly small change to get subject images from the project's CDN instead of the hard-coded list in this PR. I can work on this myself although it might take some time as I haven't done iOS development before. But if someone else here is interested please go for it.

Also I'd love to see this support an offline download, similar to how Tsurukame supports downloading fonts and audio. I don't think it would be terribly efficient to download every subject image individually so I would raise this with the project admins to consider adding a zip download that packages subject images by level (e.g. separate packages for levels 1-10, 11-20, etc like Tsurukame appears to use for audio).

Thoughts? I've been thinking about doing this in Tsurukame for the last few months but haven't found the time yet to look into it seriously. I also wasn't sure whether there would be interest in supporting a community (rather than official) source like this but when I saw this new feature mentioned I figured it was a good time to bring this up :)

2024-01-02 05:34 UTC, tallerasaf commented
@davidsansome @aaron-meyers 

Fix this in [PR - "Add ArtWork by @AmandaBear to Subject #653"](https://github.com/davidsansome/tsurukame/pull/653/files)

2024-01-02 05:48 UTC, aaron-meyers commented
I think you meant https://github.com/davidsansome/tsurukame/pull/685

2024-01-03 01:03 UTC, davidsansome commented
> That said, I'd like to propose that Tsurukame adopt the much broader AI mnemonic images project that has been ongoing for the last 1+ year.

I'd be supportive if somebody wants to implement that in Tsurukame!

> Also I'd love to see this support an offline download, similar to how Tsurukame supports downloading fonts and audio. I don't think it would be terribly efficient to download every subject image individually so I would raise this with the project admins to consider adding a zip download that packages subject images by level (e.g. separate packages for levels 1-10, 11-20, etc like Tsurukame appears to use for audio).

Agreed, I'd prefer to make these available offline. I actually changed the way Tsurukame does offline audio back in 20f5c8c014cb3e3bca2b2b04a0edacdd09240fd9 - it doesn't use the bundles any more because they got out of date as Wanikani added new audio files and voice actors. Now it downloads all the individual files from Wanikani (for all levels up to your current level + 1) in parallel. I imagine we'd do something similar for the artwork as well. It ends up being pretty fast if you do enough requests in parallel.

2024-01-03 02:03 UTC, tallerasaf commented
@davidsansome I can implement it when I have time, I think it's a very nice feature to add.

@aaron-meyers You can create an issue for this feature? And I will create a PR when I have time.

2024-01-07 03:53 UTC, aaron-meyers commented
Yeah just got back from a wedding. Will try to create the new issue over the weekend.

2024-01-10 20:28 UTC, aaron-meyers commented
Ok created a meta-feature #689 and sub-features to capture the work needed. Thanks!