Add extra practice methods: Review recent mistakes, review burned items
davidsansome/tsurukame pull request #674
Opened 2023-12-27 04:33 UTC by Deadpikle

This PR adds two new practice features to the app: review recent mistakes and review burned items.

### Practice: Review Recent Mistakes

Works like the website. You can review mistakes from the last 24 hours. Readings and meanings are grouped like on the website. This PR does not add the "redo lessons" feature like the website has.

Because [the API does not currently let you get review history](https://community.wanikani.com/t/api-changes-get-all-reviews/61617), however, this is only a local cache of recent mistakes. In theory, if/when that API comes back, this functionality will need to be updated/enhanced.

UI to get here is on the main screen and in the "Upcoming Reviews" section.

### Practice: Review Burned Items

Works like the website. You can review all your burned items review-style. Readings and meanings are grouped like on the website. I believe the WK website lets you practice all your burned items but doesn't repeat in between sessions until you have reviewed them all again. Right now, the app just throws all the burned items into a review session.

UI to get here is on the main screen all the way at the bottom under the "Burned" category.

### Potential issue

I think, for the practice sessions noted above, any changes to custom user data (custom meaning/reading explanation) aren't saved to the database. Am I reading the code correctly in that case? If so, this is probably a problem, since presumably a user might be using the explanation features when practicing recent mistakes. How should this best be solved? A refactor of `LocalCachingClient.sendProgress`? A new function to just save newer explanation data?

### Additional note

This should set up things pretty nicely for a "Recent Lessons" practice just like on the website. I'm not sure what to consider a "recent" lesson, however, so I didn't do anything with that. But it should be pretty easy to set that up now once a "recent" lesson is defined.

### Fixes

Fixes #672

2023-12-28 07:16 UTC, davidsansome commented
> I think, for the practice sessions noted above, any changes to custom user data (custom meaning/reading explanation) aren't saved to the database. Am I reading the code correctly in that case?

It looks like `ReviewSession.addSynonym` does its thing even if `isPracticeSession` is true, so it should work okay. Did something not work when you tested it?

2023-12-28 07:16 UTC, davidsansome requested changes

2023-12-28 07:16 UTC, davidsansome commented on ios/LocalCachingClient.swift
> +      if assignment!.hasPassedAt == false {
`assignment` might be nil here - you should check it with an `if let assignment = ...` instead of asserting.

2023-12-28 07:16 UTC, davidsansome commented on ios/LocalCachingClient.swift
> +        "WHERE srs_stage >= 1 AND last_mistake_time >= \"\(formatter.string(from: dayAgo))\"")
Use `\(SRSStage.apprentice1.rawValue)` here like above?

2023-12-28 07:16 UTC, davidsansome commented on ios/MainViewController.swift
> +    let recentLessons = services.localCachingClient.getAllRecentLessonAssignments()
It might be more efficient to add a separate `getAllRecentLessonAssignmentCount()` method that does a `SELECT COUNT(*)`. At the moment this is fetching a lot of data on every load of this page.

You could also consider caching the value for this one (with `@Cached`) since it doesn't depend on the current time. You'd need to invalidate it in `sendProgress`.

2023-12-28 09:04 UTC, Deadpikle commented on ios/MainViewController.swift
> +    let recentLessons = services.localCachingClient.getAllRecentLessonAssignments()
I don't know that a `COUNT(*)` will work here as the only way to get an accurate count is to look at the `TKMAssignment.hasPassedAt` field, which isn't accessible in the database without loading the data. Maybe there's something I'm overlooking. In any case, I updated it to use a cache of the count value with the invalidation as you noted.

2023-12-28 09:09 UTC, Deadpikle commented
Thanks for the review. I've updated the code per your change requests and rebased on `master`. (Which greatly simplifies my commits since now the copyright year for most things has been updated, haha. Thanks for updating that.)

> > I think, for the practice sessions noted above, any changes to custom user data (custom meaning/reading explanation) aren't saved to the database. Am I reading the code correctly in that case?
> 
> It looks like `ReviewSession.addSynonym` does its thing even if `isPracticeSession` is true, so it should work okay. Did something not work when you tested it?

Ah. You're right. I retested. Works fine and as one would expect. Have edited the original post. My fault.

2023-12-29 01:34 UTC, davidsansome commented on ios/MainViewController.swift
> +    let recentLessons = services.localCachingClient.getAllRecentLessonAssignments()
Ah yes I missed that. This looks fine then!

2023-12-29 01:34 UTC, davidsansome commented
This looks great, thanks for making these changes!

2023-12-29 01:34 UTC, merged

2024-01-02 10:17 UTC, Deadpikle commented
This is just a comment for documentation/future searches if it ever comes up: Right now, for recent mistakes, if you get it right again within 24 hrs, Tsurukame will no longer consider it a recent mistake. [This behavior matches WaniKani per this forum post announcing the feature.](https://community.wanikani.com/t/new-recent-mistakes-dashboard-component/62961)

> Q. A Recent Mistake I had in the past 24 hours disappeared, what happened?
> Most likely, you got that item correct in a Reviews session after getting it wrong in a previous Reviews session. If you get an item correct in a Reviews session before 24 hours have gone by, it disappears from the Recent Mistakes list.

So mistakes within 24 hrs that you then get correct in a subsequent review session should be and will be cleared from recent mistakes.