Fixes recent mistakes not sticking around after sync, cached #'s not being invalidated after logout/login
davidsansome/tsurukame pull request #677
Opened 2023-12-30 10:39 UTC by Deadpikle

My last PR, #674, had a small issue where recent mistakes were not sticking around in the database after an online assignment fetch due to `subject_progress` being wiped via a `REPLACE INTO` statement in `LocalCachingClient.fetchAssignments`. Instead of using `REPLACE INTO`, performs an `UPDATE` followed by an `INSERT` if the `UPDATE` did nothing.

Also fixes an issue I found where logging out of one account into another account without restarting the app didn't clear cached numbers in `LocalCachingClient`. Fixes this by invalidating items in `LocalCachingClient.clearAllData`. Also noticed that a force refresh would not clear the recent lesson count cached number from the web, so I also invalidated that on `sync`.

2023-12-30 22:25 UTC, davidsansome requested changes
Thanks for catching this bug!

2023-12-30 22:25 UTC, davidsansome commented on ios/LocalCachingClient.swift
> +          db.mustExecuteUpdate("UPDATE subject_progress SET level = ?, " +
I think you might be able to do all this all in one statement with an [upsert](https://www.sqlite.org/lang_upsert.html).

Something like:

```
INSERT INTO subject_progress (...) VALUES (...)
ON CONFLICT (id) DO UPDATE SET ...;
```

2023-12-31 01:20 UTC, Deadpikle commented
Done and tested on iOS 17. That should work nicely.

Note for the future if it ever comes up: SQLite allows for this functionality as of version `3.24.0`. iOS [changes SQLite versions over time](https://stackoverflow.com/a/35993775/3938401), but iOS 12 has version `3.24.0`. Fortunately, Tsurukame also has a minimum version of iOS 12, so it should be fine to implement it this way. 👍

(P.S. Happy almost New Year!)

2023-12-31 01:26 UTC, davidsansome commented
> Done and tested on iOS 17. That should work nicely.
> 
> Note for the future if it ever comes up: SQLite allows for this functionality as of version `3.24.0`. iOS [changes SQLite versions over time](https://stackoverflow.com/a/35993775/3938401), but iOS 12 has version `3.24.0`. Fortunately, Tsurukame also has a minimum version of iOS 12, so it should be fine to implement it this way. 👍
> 
> (P.S. Happy almost New Year!)

Sweet, thanks for checking!
Happy new year to you too!

2023-12-31 01:28 UTC, merged